      SUBROUTINE INIT_CLUSTERS(POS, VEL, BOX_SIZE, NUM_PARTICLES,
     &    CLUSTER1_FRACTION, R_C, BETA)
        IMPLICIT NONE
        REAL*8 POS(3, *), VEL(3, *), BOX_SIZE, R_C, BETA
        INTEGER NUM_PARTICLES
        REAL*8 CLUSTER1_FRACTION
        INTEGER I
        REAL*8 R, THETA, PHI, X, Y, Z
        REAL*8 CLUSTER1_CENTER(3), CLUSTER2_CENTER(3)
        REAL*8 RAND_ARRAY(3)
        INTEGER SEED(1)

        DATA CLUSTER1_CENTER /0.25D0, 0.5D0, 0.5D0/
        DATA CLUSTER2_CENTER /0.75D0, 0.5D0, 0.5D0/

        CALL RANDOM_NUMBER(RAND_ARRAY)
        SEED(1) = INT(SUM(RAND_ARRAY * 100000.0D0)) + 1
        CALL RANDOM_SEED(PUT=SEED)

        DO I = 1, INT(NUM_PARTICLES * CLUSTER1_FRACTION)
          CALL RANDOM_NUMBER(RAND_ARRAY)
          R = R_C * (RAND_ARRAY(1) ** (1.0D0 / BETA))
          THETA = ACOS(2.0D0 * RAND_ARRAY(2) - 1.0D0)
          PHI = 2.0D0 * 3.141592653589793D0 * RAND_ARRAY(3)

          X = R * SIN(THETA) * COS(PHI)
          Y = R * SIN(THETA) * SIN(PHI)
          Z = R * COS(THETA)

          POS(1, I) = CLUSTER1_CENTER(1) * BOX_SIZE + X
          POS(2, I) = CLUSTER1_CENTER(2) * BOX_SIZE + Y
          POS(3, I) = CLUSTER1_CENTER(3) * BOX_SIZE + Z
          VEL(1:3, I) = 0.0D0
        ENDDO

        DO I = INT(NUM_PARTICLES * CLUSTER1_FRACTION) + 1, NUM_PARTICLES
          CALL RANDOM_NUMBER(RAND_ARRAY)
          R = R_C * (RAND_ARRAY(1) ** (1.0D0 / BETA))
          THETA = ACOS(2.0D0 * RAND_ARRAY(2) - 1.0D0)
          PHI = 2.0D0 * 3.141592653589793D0 * RAND_ARRAY(3)

          X = R * SIN(THETA) * COS(PHI)
          Y = R * SIN(THETA) * SIN(PHI)
          Z = R * COS(THETA)

          POS(1, I) = CLUSTER2_CENTER(1) * BOX_SIZE + X
          POS(2, I) = CLUSTER2_CENTER(2) * BOX_SIZE + Y
          POS(3, I) = CLUSTER2_CENTER(3) * BOX_SIZE + Z
          VEL(1:3, I) = 0.0D0
        ENDDO

      RETURN
      END SUBROUTINE INIT_CLUSTERS

